### ISSUE TITLE
Идеи для тестов

### ISSUE THREAD

**Issue by roman-khazanskii** [Vlbager/Nandaka#2]
1. Предлагаю называть тесты по шаблону "Дано_Ожидается", а не просто "Дано".
Т.е. вместо "DoubleStartByte" будет "DoubleStartByte_ShouldParse", а вместо "WrongHeaderChecksum" будет "WrongHeaderChecksum_ShouldNotParse". 

Разделители на усмотрение соглашения по именам, есесно.

Или, если у тестового фреймворка есть какое-то специально отведенное место для указания, что ожидается, то заюзать его.

2. Можно докинуть вот таких тестов:

- Корректное сообщение с полностью корректным заголовком внутри: 
`uint8_t correctMsgSize16_withCorrectHeadCrcInside[16] = {0xBB, 0x88, 0x10, 0x8C, 0xBB, 0xCC, 0xBB, 0x04, 0x08, 0xE1, 0x00, 0xBB, 0x88, 0x08, 0x76, 0xED};`

- Несколько валидных сообщений подряд.
- Валидное сообщение, потом мусор, потом валидное сообщение.
- Сообщение с кривым заголовком, а потом валидное.
- Сообщение с кривой crc, а потом валидное.
- Пачка нулей.
- Огрызок валидного сообщения (т.е. не все ожидаемые байты после правильного заголовка), а потом валидное сообщение.

**Comment by Vlbager** [comment]
Кажется тут тоже можно закрыть. Все перечисленные тесты в том или ином виде реализованы
