### ISSUE TITLE
Права и обязанности сессии

### ISSUE THREAD

**Issue by rumkit** [Vlbager/Nandaka#3]
Как известно есть два стула...
А именно:

- либо сессия ничего не знает кроме обмена регистрами
- либо сессия дергает callback, когда не понимает, что делать с сообщениями из парсера 

В первом случае придется очень сильно заморачиваться на синхронизации потоков пишущих в композер (конкретнее придется добиться, чтобы снаружи в протокол можно было отправить команду только в промежутке между запрос-ответами).
Во втором случае видимо придется делать downcast интерфейса `IMessage` к конкретному типу сообщения от парсера, и точно так же давать команду сесии "как будет время отправь этот DeviceSpesific", но уже с upcast'ом.

Хотелось бы чтобы у меня в ближайшее время появилась идея, как усидеть на двух стульях.

**Comment by Vlbager** [comment]
Неактуально :)
