### ISSUE TITLE
PVS-Studio

### ISSUE THREAD

**Issue by roman-khazanskii** [Vlbager/Nandaka#4]
Поскольку у РТК есть лицуха, а с некоторых пор PVS умеет чекать шарповый код, считаю, что следует ее к сборке прикрутить.

Решарпер решарпером, но лишним не будет.

**Comment by Vlbager** [comment]
После многочисленных попыток запустить анализатор для проекта из под linux я все же догадался заглянуть в список поддерживаемых языков и компиляторов.
![изображение](https://user-images.githubusercontent.com/42982864/64467983-7813bd00-d127-11e9-8f68-9246ebd809e6.png)
И да, для шарпов поддерживается только из под windows...

**Comment by rumkit** [comment]
AppVeyor тебе в помощь
или azure devops
или своя виртуалка

**Comment by roman-khazanskii** [comment]
Травис вроде ж тоже винду уже может - https://docs.travis-ci.com/user/reference/windows/

**Comment by Vlbager** [comment]
Добил сборку на винде - пришлось поесть вкусного и поизучать powershell. Мне потребовалось ровно 70 попыток, чтобы все заработало.
Теперь билд и тест происходят и на линуксе, и на винде (не уверен что это оправдано).
При этом на винде устанавливается и запускается pvs, выводя в лог информацию об ошибках:
![изображение](https://user-images.githubusercontent.com/42982864/64743859-3067a980-d50a-11e9-98c8-d2c5ce7028a9.png)
Также мне приходит письмецо на почту:
![изображение](https://user-images.githubusercontent.com/42982864/64743907-57be7680-d50a-11e9-9046-7c6c7360eb54.png)
Если же ошибок нет, то все хорошо и никуда письма не отправляются:
![изображение](https://user-images.githubusercontent.com/42982864/64744139-517cca00-d50b-11e9-8a11-a23f2a8de7d9.png)

**Comment by roman-khazanskii** [comment]
https://habr.com/en/company/pvs-studio/blog/467359/

Сегодня статья вышла -_-
Если что - переезжать на азуру я не предлагаю, уже заработало и так ведь.

**Comment by Vlbager** [comment]
Вообще может быть есть смысл переехать на азуру. Тут для открытых проектов вполне себе привлекательные условия. Как-нибудь подумаю, если не будет лень)
А вообще да, все функционирует и у меня схожим образом
