### ISSUE TITLE
Device-specific и High-Prio сообщения в Каннабусе

### ISSUE THREAD

**Issue by roman-khazanskii** [Vlbager/Nandaka#5]
Тут потихоньку возобновилась работа над Канабусом на с++, поэтому повылазили всякие вопросы.

1) Сейчас в спеке прописано, что девайс-специфик сообщения могут содержать только фиксированную пачку регистров.
2) Аналогично high-prio сообщения; только регистры.

Почему для high-prio это вообще указано - неясно, вроде бы приоритет и код функции должны быть ортогональны.

Короче, встал вопрос - может, есть смысл эти ограничения убрать? Тогда:
- девайс-специфик может быть вообще произвольного содержания
- комбинируя high-prio с девайс-спецификом мы получаем возможность слейву _срать не снимая свитера_ в смысле, периодически говорить на линию самостоятельно
- запах CanOpen'a возрастет
- можно будет отдать обработку девайс-спецификов полностью на откуп пользователю библиотеки.

Малым советом эльфов (Я, Попов, Бубников) было обсуждение, возражений выражено не было. Что думаете?

**Comment by Vlbager** [comment]
Таких ограничений и не закладывалось
